alias 1=analyze
alias 2=run BruteSSH.exe; FTPCrack.exe; relaySMTP.exe; HTTPWorm.exe; SQLInject.exe; NUKE.exe; backdoor
alias stat=run fl1ght.exe
alias server=run script/purchase-servers.js
alias drain=run script/drain.js
alias c=connect
alias s=scan-analyze
alias share=run script/share.js -t 500
alias cv=run script/connect.js
alias as=run script/analyze.js
alias long=run trade/long.js; trade/dashboard.js
alias short=run trade/short.js; trade/dashboard.js
alias trade=run trade/trade.js
alias sell=run trade/sell.js
alias solo=run hack/solo.js
alias start=run start.js
alias list=buy -l
alias buyall=buy -a
alias root=run script/root.js
alias allserver=run script/allserver.js
alias go=run hack/hackfrompserv.js sigma-cosmetics; hack/solo.js joesguns
alias killall=run script/kill-all.js
alias pserv=run hack/hackfrompserv.js
alias 22=run script/purchase-servers-2-64.js
alias 33=run script/purchase-servers-3-512.js
alias 44=run script/purchase-servers-4-4096.js
alias 55=run script/purchase-servers-5-32768.js
alias 66=run script/purchase-servers-6-262144.js
alias 77=run script/purchase-servers-7-1048576.js
